name: Kitpymes.Core.Shared

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [ '7.0.100', '7.0.101' ]

    name: NET ${{ matrix.dotnet }}

    steps:  
    - uses: actions/checkout@v3
     
    - name: Setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore 
      run: dotnet restore
       
    - name: Build 
      run: dotnet build Solution.sln --configuration Release --no-restore
     
    - name: Tests
      run: dotnet test --configuration Release --no-build --no-restore
