name: Kitpymes.Core.Shared

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [ '5.0.100', '5.0.6', '5.0.7' ]

    name: Build for .NET Core ${{ matrix.dotnet }}

    steps:  
    - uses: actions/checkout@v1
     
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Clean
      run: dotnet clean Solution.sln --configuration Release && dotnet nuget locals all --clear

    - name: Install dependencies
      run: dotnet restore Project.sln
       
    - name: Build 
      run: dotnet build Solution.sln --configuration Release --no-restore
     
    - name: Tests
      run: dotnet test --configuration Release --no-build --no-restore --verbosity normal
