name: Kitpymes.Core.Shared

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [ '3.0', '3.1.x', '5.0.x' ]

    name: Build for .NET Core ${{ matrix.dotnet }}

    steps:  
    - uses: actions/checkout@v2
     
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Clean
      run: dotnet clean Solution.sln --configuration Release && dotnet nuget locals all --clear

    - name: Build 
      run: dotnet build Solution.sln --configuration Release --no-restore
     
    - name: Tests
      run: dotnet test --configuration Release --no-build --no-restore --verbosity normal
