name: Kitpymes.Core.Shared

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [ '5.0.100' ]

    name: Build for .NET Core ${{ matrix.dotnet }}

    steps:  
    - uses: actions/checkout@v1
     
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
       
    - name: Build 
      run: dotnet build Solution.sln --configuration Release
     
    - name: Tests
      run: dotnet test --configuration Release --no-build --no-restore